name: Gatsby Publish

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: enriikke/gatsby-gh-pages-action@v2.2.0
              with:
                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
                  deploy-branch: gh-pages
