#name: Gatsby Publish

#on:
#push:
#branches:
#- master
#jobs:
#build:
#if: "!contains(github.event.commits[0].message, '[skip dp]')"
#runs-on: ubuntu-latest
#steps:
#- uses: actions/checkout@v3
#- uses: enriikke/gatsby-gh-pages-action@v2.2.1
#with:
#access-token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#deploy-branch: gh-pages
#env:
#GATSBY_API_URL: ${{ secrets.GATSBY_API_URL }}
#GATSBY_API_KEY: ${{ secrets.GATSBY_API_KEY }}
