name: Deploy-Build-React

on:
  push:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci
          CI=false npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' && github.event.pull_request.merged }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
