name: Testing

on:
  pull_request:
  push:
    branches:
      - dev
      - master

jobs:
  test:
    name: Test code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: |
          npm ci
          CI=false npm run test
